name: schmgtsystem
description: A new Flutter project.

publish_to: "none" # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  collection: ^1.18.0
  easy_sidemenu: ^0.6.1
  flutter_timetable: ^1.1.6
  intl:
  iconsax:
  fl_chart:
  equatable: ^2.0.7
  printing: ^5.11.0
  pdf: ^3.10.4
  file_picker: ^6.1.1
  image_picker:
  data_table_2: ^2.6.0
  excel: ^2.0.6
  file_saver: ^0.1.1
  http:
  fluttertoast:
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  flutter_animate: ^4.2.0+1
  get_it: ^7.7.0
  dio: ^5.7.0
  flutter_easyloading: ^3.0.3
  flutter_styled_toast: ^2.1.3
  flutter_riverpod: ^1.0.3
  shared_preferences: ^2.3.2
  go_router: ^12.0.0
  image: ^4.1.7
  country_picker: ^2.0.21
  pdf_render: ^1.4.0
  
  
  
    
  



  flutter_localization: ^0.3.2

  syncfusion_flutter_charts:
  url_launcher:
  provider:
  # charts_flutter:

  path_provider: ^2.0.15
  uuid: ^3.0.7
  flutter_quill: ^11.4.0
  flutter_quill_extensions:
  toastification: 
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Updated to latest version
  # hive_generator: ^2.0.1
  # build_runner: ^2.4.6

flutter:
  uses-material-design: true

  # Uncomment and add your image assets here
  assets:
    - assets/images/

  # Uncomment and configure if you want to use custom fonts
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
